# rustfmt configuration
edition = "2021"

# Basic formatting
max_width = 100
hard_tabs = false
tab_spaces = 4

# Import formatting
imports_granularity = "Crate"
reorder_imports = true
reorder_modules = true

# Other formatting options
use_field_init_shorthand = true
use_try_shorthand = true
newline_style = "Unix"