# rustfmt configuration
edition = "2021"

# Basic formatting
hard_tabs  = false
max_width  = 100
tab_spaces = 4

# Import formatting
imports_granularity = "Crate"
reorder_imports     = true
reorder_modules     = true

# Other formatting options
newline_style            = "Unix"
use_field_init_shorthand = true
use_try_shorthand        = true
